spring:
  application:
    name: date-school
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/date?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9091
mybatis:
  type-aliases-package: com.dhrs.date.pojo
  #   驼峰命名
  configuration:
    map-underscore-to-camel-case: true
