spring:
  application:
    name: date-school
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/date?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 119.23.49.175:8848
server:
  port: 8002
mybatis:
  type-aliases-package: com.dhrs.date.common.entity.school
  #   驼峰命名
  configuration:
    map-underscore-to-camel-case: true
