server:
  port: 8004
spring:
  application:
    name: date-third
  cloud:
    nacos:
      discovery:
        server-addr: 119.23.49.175:8848
date:
  sms:
    accessKeyId: LTAI4FctpuMr8YWHuXdnXDvi # 你自己的accessKeyId
    accessKeySecret: AWrBcrVQcIvFWfV7Q18cN27TLOOCzQ # 你自己的AccessKeySecret
    signName: 成工商城 # 签名名称
    verifyCodeTemplate: SMS_178765813 # 模板名称
  obs:
    endPoint: https://obs.cn-north-4.myhuaweicloud.com
    ak: XYGWIZMVBLXGVYDMEWLA
    sk: TfIv3IuFO8fIF12A2VYP5y2WCdxnLuW5Mhf2vxzb